version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lokanta_siparis_app
    ports:
      - "8000:80" # Host port 8000 -> Container port 80 (Apache)
    volumes:
      # Proje dizinini container içine mount et (kod değişiklikleri için)
      # vendor ve database hariç tutulur, bunlar container içinde yönetilir
      - .:/var/www/html
      - /var/www/html/vendor # vendor klasörünü volume olarak tanımla (hosttan üzerine yazılmasın)
    environment:
      DB_HOST: postgres # PostgreSQL servis adı
      DB_PORT: 5432
      DB_DATABASE: lokanta_db
      DB_USERNAME: lokanta_user
      DB_PASSWORD: lokanta_password
      # APP_ENV: development # Gerekirse ortamı ayarlayın
    depends_on:
      - postgres # App servisi başlamadan önce postgres servisinin başlamasını bekle
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine # PostgreSQL imajı
    container_name: lokanta_postgres_db
    environment:
      POSTGRES_DB: lokanta_db # Veritabanı adı
      POSTGRES_USER: lokanta_user # Kullanıcı adı
      POSTGRES_PASSWORD: lokanta_password # Şifre
    volumes:
      - postgres_data:/var/lib/postgresql/data # Verilerin kalıcı olması için volume
    ports:
      - "5432:5432" # Opsiyonel: Hosttan direk erişim için (geliştirme sırasında)
    restart: unless-stopped

volumes:
  postgres_data: # PostgreSQL verileri için named volume 